### ISSUE TITLE
read kafka message as json

### ISSUE THREAD

**Issue by ZhijiaYang** [justsocialapps/kafkabeat#1]
I have try this model: logfile --> filebeat --> kafka --> logstash --> elasticsearch -- >kibana.

I try to replace logstash with your kafkabeat. 

But all message look like this:
{
  "@timestamp": "2017-09-05T03:12:16.331Z",
  "@metadata": {
    "beat": "\u003cnot set\u003e",
    "type": "doc"
  },
  "message": "{\"@timestamp\":\"2017-09-05T03:11:40.064Z\",\"beat\":{\"hostname\":\"ip-166-61\",\"name\":\"ip-166-61\",\"version\":\"5.5.2\"},\"fields\":{\"app_name\":\"probe\",\"conatiner_name\":\"helloworld-2\",\"space_id\":\"test-space\"},\"input_type\":\"log\",\"message\":\"hi probe log line\",\"offset\":504,\"source\":\"/log/example/probe.log\",\"type\":\"log\"}",
  "beat": {
    "version": "6.0.0-beta1",
    "name": "179-38",
    "hostname": "179-38"
  },
  "type": "179-38"
}

The kafka message will be one of json filed.

Does kafkabeat support 'codec' just like in logstash ?

**Comment by makkes** [comment]
Thanks for your feedback. We are currently using kafkabeat to feed Kafka messages into Logstash (`kafka --> logstash --> elasticsearch`). Our Logstash configuration looks like this:
```
input {
  beats {
[...]
    codec => "json"
[...]
  }
}
```
This way, logstash does the work of decoding JSON messages for us. Would you be able to try this approach?

**Comment by ZhijiaYang** [comment]
Thank you for your response. It is work.
I just want to try some fun, 
from
 `logfile --> filebeat --> kafka --> logstash --> elasticsearch -- >kibana`  
to
`logfile --> filebeat --> kafka --> kafkabeat--> elasticsearch -- >kibana`

I think kafkabeat is simple and light.
But,   beats is a collector.
Maybe, we always need only one beat to 'ship from source'.

**Comment by makkes** [comment]
Yeah, running kafkabeat instead of Logstash on your source server will definitely spare you some resources, since Beats are generally built to consume as few hardware resources as possible. The easiest solution is to just run only one Logstash instance (on a remote server) and let kafkabeat feed it with messages.

**Comment by makkes** [comment]
Is there anything I can do to help you with this? Otherwise I would close this issue for now.

**Comment by ZhijiaYang** [comment]
thank you. no more question.
